import type { QuizQuestion } from "./types";

const QUESTIONS: QuizQuestion[] = [
  // ---- young (כיתות א'-ב') ----
  {
    id: "english-001",
    prompt: 'איך אומרים "חתול" באנגלית?',
    choices: ["dog", "cat", "cow", "cup"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-002",
    prompt: 'איך אומרים "כלב" באנגלית?',
    choices: ["dog", "dig", "deer", "duck"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "english-003",
    prompt: 'איך אומרים "ספר" באנגלית?',
    choices: ["pen", "paper", "book", "bag"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "english-004",
    prompt: 'איך אומרים "מים" באנגלית?',
    choices: ["wine", "water", "milk", "juice"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-005",
    prompt: 'איך אומרים "שמש" באנגלית?',
    choices: ["sun", "son", "sea", "sky"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "english-006",
    prompt: 'איך אומרים "ירח" באנגלית?',
    choices: ["star", "moon", "month", "morning"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-007",
    prompt: 'איך אומרים "בית" באנגלית?',
    choices: ["home", "house", "hotel", "hat"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-008",
    prompt: 'איך אומרים "אדום" באנגלית?',
    choices: ["red", "read", "rod", "ride"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "english-009",
    prompt: 'איך אומרים "כחול" באנגלית?',
    choices: ["black", "brown", "blue", "blew"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "english-010",
    prompt: 'איך אומרים "ירוק" באנגלית?',
    choices: ["grin", "green", "gray", "great"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-011",
    prompt: 'איך אומרים "אמא" באנגלית?',
    choices: ["mother", "father", "sister", "brother"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "english-012",
    prompt: 'איך אומרים "אבא" באנגלית?',
    choices: ["father", "uncle", "grandfather", "friend"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "english-013",
    prompt: 'מה זה "apple"?',
    choices: ["תפוז", "תפוח", "ענב", "אגס"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-018",
    prompt: 'איך אומרים "שבע" באנגלית?',
    choices: ["six", "seven", "eight", "nine"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-019",
    prompt: 'איך אומרים "עשר" באנגלית?',
    choices: ["ten", "twenty", "tin", "tan"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "english-025",
    prompt: 'מה זה "big"?',
    choices: ["קטן", "גדול", "ארוך", "קצר"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "english-026",
    prompt: 'איך אומרים "אחת" באנגלית?',
    choices: ["one", "two", "three", "ten"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "english-027",
    prompt: 'מה זה "banana"?',
    choices: ["תפוח", "בננה", "אגס", "גזר"],
    correctIndex: 1,
    level: "young",
  },

  // ---- middle (כיתות ג'-ה') ----
  {
    id: "english-014",
    prompt: 'מה זה "school"?',
    choices: ["בית-חולים", "בית-כנסת", "בית-ספר", "בית-קפה"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "english-015",
    prompt: 'מה זה "teacher"?',
    choices: ["מורה", "תלמיד", "רופא", "טבח"],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "english-016",
    prompt: 'מה זה "happy"?',
    choices: ["עצוב", "כועס", "שמח", "עייף"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "english-017",
    prompt: 'מה זה "friend"?',
    choices: ["אויב", "חבר", "קרוב משפחה", "שכן"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-020",
    prompt: 'איך אומרים "יום ראשון" באנגלית?',
    choices: ["Monday", "Sunday", "Saturday", "Friday"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-021",
    prompt: 'מה זה "to read"?',
    choices: ["לכתוב", "לקרוא", "לרוץ", "לישון"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-022",
    prompt: 'מה זה "to eat"?',
    choices: ["לאכול", "לשתות", "לשחק", "לחשוב"],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "english-023",
    prompt: 'איך אומרים "ים" באנגלית?',
    choices: ["see", "sea", "say", "sky"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-024",
    prompt: 'איך אומרים "חורף" באנגלית?',
    choices: ["summer", "spring", "winter", "fall"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "english-028",
    prompt: 'מה ההפך של "big"?',
    choices: ["small", "tall", "long", "wide"],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "english-029",
    prompt: 'מה ההפך של "hot"?',
    choices: ["warm", "cold", "cool", "wet"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-030",
    prompt: 'מה צורת הרבים של "child"?',
    choices: ["childs", "childes", "children", "childrens"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "english-031",
    prompt: 'מה צורת הרבים של "mouse"?',
    choices: ["mouses", "mice", "mouse", "mices"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-032",
    prompt: 'השלימו: "I ___ a student."',
    choices: ["am", "is", "are", "be"],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "english-033",
    prompt: 'השלימו: "She ___ to school every day."',
    choices: ["go", "goes", "going", "gone"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-034",
    prompt: 'מה זה "kitchen"?',
    choices: ["חדר שינה", "מטבח", "סלון", "מרפסת"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "english-035",
    prompt: 'מה זה "always"?',
    choices: ["לפעמים", "אף פעם", "תמיד", "מחר"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "english-036",
    prompt: "איזו מילה מתארת מזג אוויר?",
    choices: ["rainy", "table", "shoe", "pencil"],
    correctIndex: 0,
    level: "middle",
  },

  // ---- older (כיתות ו' ומעלה) ----
  {
    id: "english-037",
    prompt: 'מה זה "to borrow"?',
    choices: ["להשאיל", "ללוות (לקחת בהשאלה)", "לקנות", "למכור"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-038",
    prompt: 'מה זה "expensive"?',
    choices: ["זול", "יקר", "חינם", "שבור"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-039",
    prompt: 'מה ההפך של "expensive"?',
    choices: ["cheap", "rich", "poor", "early"],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "english-040",
    prompt: 'השלימו: "Yesterday I ___ to the park."',
    choices: ["go", "went", "gone", "going"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-041",
    prompt: 'השלימו: "They ___ watching TV now."',
    choices: ["is", "am", "are", "be"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "english-042",
    prompt: 'מה זה "decision"?',
    choices: ["שאלה", "החלטה", "תשובה", "הזמנה"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-043",
    prompt: 'מה זה "to improve"?',
    choices: ["להרוס", "לשפר", "לשכוח", "להפסיק"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-044",
    prompt: 'מה הפירוש של "I am looking forward to the trip"?',
    choices: ["אני מפחד מהטיול", "אני מצפה לטיול בקוצר רוח", "אני מוותר על הטיול", "שכחתי מהטיול"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-045",
    prompt: 'מה צורת העבר של "to buy"?',
    choices: ["buyed", "bought", "buys", "buying"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-046",
    prompt: 'מה זה "salary"?',
    choices: ["מתנה", "משכורת", "חיסכון", "קנס"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-047",
    prompt: 'מה זה "although"?',
    choices: ["בגלל", "למרות ש...", "כאשר", "אם"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-048",
    prompt: "איזו מילה היא שם תואר (adjective)?",
    choices: ["quickly", "beautiful", "run", "happiness"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-049",
    prompt: 'השלימו: "If it rains, we ___ stay home."',
    choices: ["will", "did", "was", "were"],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "english-050",
    prompt: 'מה זה "neighbor"?',
    choices: ["חבר", "שכן", "אורח", "קרוב משפחה"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "english-051",
    prompt: 'מה ההפך של "to remember"?',
    choices: ["to forget", "to forgive", "to repeat", "to return"],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "english-052",
    prompt: 'מה זה "future"?',
    choices: ["עבר", "הווה", "עתיד", "עכשיו"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "english-053",
    prompt: 'מה צורת העבר של "to go"?',
    choices: ["goed", "gone", "went", "going"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "english-054",
    prompt: 'מה הפירוש של "She has lived here for five years"?',
    choices: [
      "היא גרה כאן כבר חמש שנים",
      "היא גרה כאן לפני חמש שנים ועזבה",
      "היא תגור כאן בעוד חמש שנים",
      "היא ביקרה כאן לפני חמש שנים",
    ],
    correctIndex: 0,
    level: "older",
  },
];

export default QUESTIONS;
