import type { QuizQuestion } from "./types";

const QUESTIONS: QuizQuestion[] = [
  // ---- young (כיתות א'-ב') ----
  {
    id: "finance-001",
    prompt: "מה זה לחסוך?",
    choices: ["להוציא את כל הכסף", "לשמור חלק מהכסף לעתיד", "לתת את הכסף לחברים", "לזרוק את הכסף"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-002",
    prompt: 'מה ההבדל בין "צריך" ל"רוצה"?',
    choices: [
      "אין הבדל",
      'ל"צריך" אי אפשר לוותר, ל"רוצה" כן',
      'ל"רוצה" אי אפשר לוותר',
      "שניהם בדיוק אותו דבר",
    ],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-010",
    prompt: 'מה זה "מטבע"?',
    choices: ["כסף עגול ממתכת", "סוג של אוכל", "משחק", "ספר"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "finance-011",
    prompt: "המטבע של ישראל נקרא:",
    choices: ["דולר", "יורו", "שקל", 'ליש"ט'],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "finance-014",
    prompt: "מה הכי כדאי לעשות עם דמי כיס?",
    choices: ["להוציא הכל מיד", "לאבד אותם", "לחלק לחיסכון ולהוצאה", "להעביר לאחר"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "finance-021",
    prompt: 'מה מהבאים הוא "צריך" אמיתי?',
    choices: ["משחק חדש", "אוכל", "צעצוע שלישי", "ממתק"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-022",
    prompt: 'מה זה "מתנה"?',
    choices: ["משהו שמשלמים עליו", "משהו שמקבלים בלי לשלם", "סוג של הלוואה", "מה שמוציאים בחנות"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-024",
    prompt: 'מה זה "מחיר"?',
    choices: ["שם המוצר", "כמה הוא עולה", "צבע המוצר", "מי קונה אותו"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-025",
    prompt: "אם אתה מוציא כל מה שאתה מקבל, מה ייקרה כשתרצה משהו גדול?",
    choices: ["לא תוכל לקנות אותו", "תקבל אותו במתנה", "תוכל להוציא יותר", "המחיר ירד"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "finance-026",
    prompt: "איפה הכי טוב לשמור מטבעות שאוספים?",
    choices: ["בקופת חיסכון", "על הרצפה", "בכיס עם חור", "בחוץ"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "finance-027",
    prompt: "מה עושים עם כסף בחנות?",
    choices: ["משלמים בו על דברים", "אוכלים אותו", "זורקים אותו", "מציירים עליו"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "finance-028",
    prompt: "אם יש לך 5 ₪ וקיבלת עוד 3 ₪, כמה כסף יש לך?",
    choices: ["7 ₪", "8 ₪", "9 ₪", "10 ₪"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-029",
    prompt: "מה מהבאים אפשר לקנות בכסף?",
    choices: ["גלידה", "חיבוק", "שינה", "שמש"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "finance-030",
    prompt: 'מי מהבאים הוא "רוצה" ולא "צריך"?',
    choices: ["מים", "אוכל", "צעצוע חדש", "מעיל לחורף"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "finance-031",
    prompt: "אם החיסכון שלך גדל כל שבוע, מה זה אומר?",
    choices: ["שאתה מוציא הכל", "שאתה שומר כסף בצד", "שאיבדת כסף", "שאין לך כסף"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-032",
    prompt: "איזה מטבע שווה הכי הרבה?",
    choices: ["מטבע של 1 ₪", "מטבע של 2 ₪", "מטבע של 10 אגורות", "מטבע של 50 אגורות"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-033",
    prompt: "אם משהו עולה 10 ₪ ויש לך רק 6 ₪, האם תוכל לקנות אותו?",
    choices: ["כן", "לא", "רק בשבת", "רק עם חבר"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "finance-034",
    prompt: "מה כדאי לעשות כשמקבלים דמי כיס?",
    choices: ["לאבד אותם", "לשמור חלק בצד", "להוציא הכל באותו רגע", "לזרוק אותם"],
    correctIndex: 1,
    level: "young",
  },

  // ---- middle (כיתות ג'-ה') ----
  {
    id: "finance-003",
    prompt: "אם יש לך 50 ₪ ואתה קונה משחק ב-30 ₪, כמה נשאר?",
    choices: ["10 ₪", "15 ₪", "20 ₪", "25 ₪"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "finance-004",
    prompt: 'מה זה "תקציב"?',
    choices: ["שטר של 100 ₪", "תוכנית כמה כסף נכניס ונוציא", "סוג של חיסכון", "חנות גדולה"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-006",
    prompt: "אם חוסכים 10 ₪ כל שבוע, כמה יהיה אחרי 10 שבועות?",
    choices: ["80 ₪", "90 ₪", "100 ₪", "110 ₪"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "finance-007",
    prompt: 'מה זה "הנחה"?',
    choices: ["להוסיף עוד כסף למחיר", "להוריד מהמחיר", "לא לקנות בכלל", "להחליף מוצר"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-008",
    prompt: "מה כדאי לעשות לפני קנייה גדולה?",
    choices: [
      "לקנות מהר בלי לחשוב",
      "להשוות מחירים ולחשוב אם באמת צריך",
      "לבקש מכולם להסביר",
      "לקנות שניים ליתר ביטחון",
    ],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-012",
    prompt: "אם דמי הכיס שלך 20 ₪ בשבוע, כמה זה בחודש (4 שבועות)?",
    choices: ["60 ₪", "70 ₪", "80 ₪", "100 ₪"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "finance-013",
    prompt: 'מה זה "בנק"?',
    choices: ["חנות לבגדים", "מקום שבו שומרים ומפקידים כסף", "מסעדה", "סוג של משחק"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-015",
    prompt: "אם משהו עולה 90 ₪ במקום אחד ו-100 ₪ במקום שני, היכן עדיף לקנות (אותו מוצר)?",
    choices: ["במקום של 100 ₪", "במקום של 90 ₪", "לא משנה", "באף אחד"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-016",
    prompt: 'מה זה "הכנסה"?',
    choices: ["כסף שאתה מוציא", "כסף שאתה מקבל", "כסף שאתה מאבד", "כסף של אחרים"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-017",
    prompt: 'מה זה "הוצאה"?',
    choices: ["כסף שמגיע אליך", "כסף שאתה משלם בעבור משהו", "סוג של חיסכון", "מתנה"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-018",
    prompt: "כמה אגורות יש בשקל?",
    choices: ["10", "50", "100", "1000"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "finance-019",
    prompt: "אם יש לך מטרת חיסכון ל-200 ₪ ואתה חוסך 25 ₪ בשבוע, אחרי כמה שבועות תגיע?",
    choices: ["6", "7", "8", "10"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "finance-020",
    prompt: "למה כדאי להשוות מחירים בין חנויות?",
    choices: ["כדי לבזבז זמן", "כדי למצוא את המחיר הטוב ביותר", "כדי להיראות חכם", "אין סיבה"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-023",
    prompt: "אם חוסכים 5 ₪ כל יום למשך חודש (30 ימים), כמה נצבר?",
    choices: ["100 ₪", "120 ₪", "150 ₪", "200 ₪"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "finance-035",
    prompt: "קנית חטיף ב-4 ₪ ושילמת עם שטר של 20 ₪. כמה עודף תקבל?",
    choices: ["14 ₪", "15 ₪", "16 ₪", "18 ₪"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "finance-036",
    prompt: 'מה זה "עודף"?',
    choices: ["הכסף שמחזירים לך כששילמת יותר מהמחיר", "מס", "קנס", "הנחה"],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "finance-037",
    prompt: "מוצר עולה 100 ₪ ויש עליו הנחה של 10 ₪. כמה תשלם?",
    choices: ["80 ₪", "90 ₪", "100 ₪", "110 ₪"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "finance-038",
    prompt: "למה כדאי לקבוע מטרת חיסכון?",
    choices: ["כי זה מבלבל", "כדי לדעת לקראת מה חוסכים ולהתמיד", "כדי להוציא יותר", "אין סיבה"],
    correctIndex: 1,
    level: "middle",
  },

  // ---- older (כיתות ו' ומעלה) ----
  {
    id: "finance-005",
    prompt: "מי מדפיס את שטרות הכסף בישראל?",
    choices: ["הממשלה", "בנק ישראל", "הבנקים הפרטיים", "בית הדפוס"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-009",
    prompt: "אם יש לך 20 ₪ ואתה רוצה לחסוך 25%, כמה תחסוך?",
    choices: ["2 ₪", "5 ₪", "10 ₪", "15 ₪"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-039",
    prompt: 'מה זה "ריבית"?',
    choices: [
      "תוספת כסף שמקבלים על חיסכון או משלמים על הלוואה",
      "סוג של מטבע",
      "הנחה בחנות",
      "מס על אוכל",
    ],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "finance-040",
    prompt: "חסכת 100 ₪ בבנק עם ריבית שנתית של 5%. כמה יהיה לך אחרי שנה?",
    choices: ["100 ₪", "105 ₪", "110 ₪", "150 ₪"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-041",
    prompt: 'מה זה "אינפלציה"?',
    choices: ["עלייה כללית של המחירים לאורך זמן", "ירידת מחירים", "סוג של חיסכון", "שם של בנק"],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "finance-042",
    prompt: 'מה זה "הלוואה"?',
    choices: [
      "כסף שמקבלים במתנה",
      "כסף שלווים וצריך להחזיר, לרוב עם ריבית",
      "חיסכון בבנק",
      "משכורת",
    ],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-043",
    prompt: "אם ההכנסה החודשית שלך 80 ₪ וההוצאות 65 ₪, כמה נשאר לחיסכון?",
    choices: ["10 ₪", "15 ₪", "20 ₪", "25 ₪"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-044",
    prompt: 'מה זה "מס"?',
    choices: [
      "תשלום חובה למדינה שמממן שירותים לציבור",
      "מתנה לבנק",
      "סוג של הנחה",
      "כסף שמוצאים ברחוב",
    ],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "finance-045",
    prompt: "מוצר עולה 200 ₪ ויש עליו 25% הנחה. כמה תשלם?",
    choices: ["100 ₪", "125 ₪", "150 ₪", "175 ₪"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "finance-046",
    prompt: 'מה ההבדל בין כרטיס "חיוב מיידי" (דביט) לכרטיס אשראי?',
    choices: [
      "אין הבדל",
      "בדביט הכסף יורד מיד מהחשבון, באשראי משלמים מאוחר יותר",
      "דביט הוא רק לילדים",
      "אשראי הוא כסף חינם",
    ],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-047",
    prompt: "אם אתה חוסך 15% מדמי כיס של 40 ₪ בשבוע, כמה תחסוך בשבוע?",
    choices: ["4 ₪", "5 ₪", "6 ₪", "8 ₪"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "finance-048",
    prompt: 'מה זה "תקציב מאוזן"?',
    choices: [
      "כשההוצאות אינן גדולות מההכנסות",
      "כשמוציאים יותר ממה שמכניסים",
      "כשאין בכלל הכנסות",
      "כשקונים רק בהנחות",
    ],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "finance-049",
    prompt: "למה מסוכן להוציא יותר ממה שמכניסים לאורך זמן?",
    choices: ["זה לא מסוכן", "נכנסים לחובות", "המחירים יורדים", "הבנק שמח"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-050",
    prompt: 'מה זה "השקעה"?',
    choices: ["שימוש בכסף כדי לנסות להרוויח יותר כסף בעתיד", "בזבוז כסף", "החזר חוב", "סוג של מס"],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "finance-051",
    prompt: "חסכת 50 ₪ וקיבלת ריבית של 10%. כמה כסף יש לך עכשיו?",
    choices: ["51 ₪", "55 ₪", "60 ₪", "65 ₪"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-052",
    prompt: 'מהי "עסקה משתלמת"?',
    choices: [
      "לקנות בלי לבדוק מחיר",
      "לקבל תמורה טובה ביחס למחיר ששילמת",
      "לקנות את היקר ביותר",
      "לקנות כמה שיותר",
    ],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "finance-053",
    prompt: "אם מחיר של משחק עלה מ-50 ₪ ל-60 ₪, בכמה אחוזים הוא התייקר?",
    choices: ["10%", "15%", "20%", "25%"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "finance-054",
    prompt: "מה היתרון של חיסכון קבוע כל שבוע, אפילו בסכום קטן?",
    choices: ["אין יתרון", "הסכומים מצטברים עם הזמן לסכום גדול", "הכסף נעלם", "המחירים עולים"],
    correctIndex: 1,
    level: "older",
  },
];

export default QUESTIONS;
