import type { QuizQuestion } from "./types";

const QUESTIONS: QuizQuestion[] = [
  // ---- young (כיתות א'-ב') ----
  {
    id: "math-001",
    prompt: "כמה זה 7 + 8?",
    choices: ["14", "15", "16", "17"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-002",
    prompt: "כמה זה 12 − 5?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-009",
    prompt: "מהו המספר הבא בסדרה: 2, 4, 6, 8, ...?",
    choices: ["9", "10", "11", "12"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-013",
    prompt: "כמה דקות יש בשעה?",
    choices: ["30", "45", "60", "100"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "math-014",
    prompt: "כמה שעות יש ביממה?",
    choices: ["12", "20", "24", "30"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "math-026",
    prompt: "כמה זה 5 + 4?",
    choices: ["8", "9", "10", "11"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-027",
    prompt: "כמה זה 10 − 6?",
    choices: ["3", "4", "5", "6"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-028",
    prompt: "כמה זה 8 + 7?",
    choices: ["14", "15", "16", "13"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-029",
    prompt: "כמה זה 16 − 9?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-030",
    prompt: "כמה צלעות יש למשולש?",
    choices: ["2", "3", "4", "5"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-031",
    prompt: "כמה צלעות יש לריבוע?",
    choices: ["3", "4", "5", "6"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-032",
    prompt: "איזה מהמספרים הבאים הוא הגדול ביותר?",
    choices: ["12", "21", "19", "15"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-033",
    prompt: "כמה זה 2 + 2 + 2?",
    choices: ["4", "6", "8", "2"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-034",
    prompt: "מהו המספר הבא בסדרה: 1, 2, 3, 4, ...?",
    choices: ["4", "5", "6", "7"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-035",
    prompt: "לדנה היו 9 בלונים ו-3 התפוצצו. כמה בלונים נשארו?",
    choices: ["5", "6", "7", "8"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-036",
    prompt: "כמה זה 10 + 10?",
    choices: ["10", "20", "30", "40"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "math-037",
    prompt: "כמה אצבעות יש בשתי ידיים?",
    choices: ["5", "8", "10", "20"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "math-038",
    prompt: "כמה זה 13 + 6?",
    choices: ["18", "19", "20", "17"],
    correctIndex: 1,
    level: "young",
  },

  // ---- middle (כיתות ג'-ה') ----
  {
    id: "math-003",
    prompt: "כמה זה 6 × 7?",
    choices: ["42", "36", "48", "40"],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "math-004",
    prompt: "כמה זה 9 × 8?",
    choices: ["63", "81", "72", "64"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-005",
    prompt: "כמה זה 56 ÷ 7?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-006",
    prompt: "כמה זה 81 ÷ 9?",
    choices: ["7", "8", "9", "10"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-007",
    prompt: "כמה זה חצי מ-50?",
    choices: ["20", "25", "30", "15"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "math-008",
    prompt: "כמה זה רבע מ-100?",
    choices: ["20", "25", "40", "50"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "math-010",
    prompt: "מהו המספר הבא בסדרה: 5, 10, 15, 20, ...?",
    choices: ["22", "23", "24", "25"],
    correctIndex: 3,
    level: "middle",
  },
  {
    id: "math-011",
    prompt: "יש 4 ילדים, וכל אחד מקבל 3 סוכריות. כמה סוכריות חולקו בסך הכל?",
    choices: ["10", "11", "12", "14"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-012",
    prompt: 'אורך אחד הצדדים של ריבוע הוא 5 ס"מ. מהי ההיקף שלו?',
    choices: ["10", "15", "20", "25"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-015",
    prompt: "כמה זה 100 − 37?",
    choices: ["53", "63", "73", "67"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "math-016",
    prompt: "כמה זה 25 + 47?",
    choices: ["62", "72", "82", "73"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "math-019",
    prompt: 'אם 1 ק"ג עולה 12 ₪, כמה יעלו 3 ק"ג?',
    choices: ["24 ₪", "30 ₪", "36 ₪", "40 ₪"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-022",
    prompt: "כמה זה 8 × 6?",
    choices: ["42", "46", "48", "54"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-023",
    prompt: "מספר אי-זוגי הוא:",
    choices: ["4", "6", "9", "10"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-024",
    prompt: "איזה משבר הוא הגדול ביותר?",
    choices: ["1/2", "1/3", "1/4", "1/5"],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "math-025",
    prompt: "כמה זה 144 ÷ 12?",
    choices: ["10", "11", "12", "14"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "math-039",
    prompt: "כמה זה 7 × 9?",
    choices: ["56", "63", "72", "69"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "math-040",
    prompt: "לכיתה הגיעו 28 תלמידים והם התחלקו ל-4 קבוצות שוות. כמה תלמידים בכל קבוצה?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 1,
    level: "middle",
  },

  // ---- older (כיתות ו' ומעלה) ----
  {
    id: "math-017",
    prompt: "במשולש שווה-צלעות, כל הזוויות שוות. מהי גודלה של כל זווית?",
    choices: ["45°", "60°", "90°", "180°"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-018",
    prompt: "כמה זה 3²? (שלוש בריבוע)",
    choices: ["6", "9", "12", "27"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-020",
    prompt: "כמה זה 10% מ-200?",
    choices: ["10", "20", "30", "50"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-021",
    prompt: "כמה זה 50% מ-80?",
    choices: ["20", "30", "40", "60"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "math-041",
    prompt: "כמה זה 15% מ-200?",
    choices: ["20", "25", "30", "35"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "math-042",
    prompt: "כמה זה 0.5 + 0.25?",
    choices: ["0.30", "0.75", "0.55", "1.25"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-043",
    prompt: "כמה זה 1/2 + 1/4?",
    choices: ["2/6", "3/4", "1/6", "2/4"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-044",
    prompt: "אם 3x = 21, כמה זה x?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-045",
    prompt: 'מהו שטח מלבן באורך 8 ס"מ וברוחב 5 ס"מ?',
    choices: ['13 סמ"ר', '26 סמ"ר', '40 סמ"ר', '45 סמ"ר'],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "math-046",
    prompt: "מחיר חולצה ירד מ-80 ₪ ל-60 ₪. בכמה אחוזים ירד המחיר?",
    choices: ["20%", "25%", "30%", "15%"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-047",
    prompt: "כמה זה 2³? (שתיים בשלישית)",
    choices: ["6", "8", "9", "16"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-048",
    prompt: "מהו הממוצע של 4, 6 ו-8?",
    choices: ["5", "6", "7", "8"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-049",
    prompt: "כמה זה 30% מ-90?",
    choices: ["18", "21", "27", "30"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "math-050",
    prompt: "מהו המספר הראשוני מבין הבאים?",
    choices: ["9", "15", "17", "21"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "math-051",
    prompt: "סכום הזוויות במשולש הוא:",
    choices: ["90°", "180°", "270°", "360°"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-052",
    prompt: "כמה זה 1.2 × 10?",
    choices: ["1.20", "12", "120", "0.12"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "math-053",
    prompt: "אם 25% ממספר הם 15, מהו המספר?",
    choices: ["45", "50", "60", "75"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "math-054",
    prompt: "מהו המספר הבא בסדרה: 1, 1, 2, 3, 5, 8, ...?",
    choices: ["11", "12", "13", "15"],
    correctIndex: 2,
    level: "older",
  },
];

export default QUESTIONS;
