import type { QuizQuestion } from "./types";

const QUESTIONS: QuizQuestion[] = [
  // ---- young (כיתות א'-ב') ----
  {
    id: "torah-001",
    prompt: "מי היה האדם הראשון לפי התורה?",
    choices: ["נח", "אברהם", "אדם", "משה"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-003",
    prompt: "מי הוציא את בני ישראל ממצרים?",
    choices: ["יוסף", "משה", "אהרון", "יהושע"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "torah-004",
    prompt: "כמה הם עשרת הדיברות?",
    choices: ["7", "10", "12", "13"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "torah-006",
    prompt: "כמה הם חמשת חומשי תורה?",
    choices: ["3", "4", "5", "6"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-007",
    prompt: "מי היו שלושת האבות?",
    choices: ["אברהם, יצחק, יעקב", "משה, אהרון, מרים", "שאול, דוד, שלמה", "אדם, נח, שם"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "torah-009",
    prompt: "באיזה חג אוכלים מצה?",
    choices: ["חנוכה", "פסח", "סוכות", "פורים"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "torah-013",
    prompt: "באיזה חג אוכלים בסוכה?",
    choices: ["פורים", "חנוכה", "סוכות", 'ל"ג בעומר'],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-019",
    prompt: "מה הוא היום השביעי לפי התורה?",
    choices: ["יום שלישי", "יום שישי", "שבת", "ראש חודש"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-023",
    prompt: 'איזה ספר פותח את התנ"ך?',
    choices: ["שמות", "ויקרא", "בראשית", "במדבר"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-026",
    prompt: "מה ברא אלוהים ביום הראשון לפי התורה?",
    choices: ["את האור", "את החיות", "את האדם", "את הים"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "torah-027",
    prompt: "בכמה ימים נברא העולם (לא כולל יום המנוחה)?",
    choices: ["5", "6", "7", "8"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "torah-028",
    prompt: "מי בנה את התיבה?",
    choices: ["אברהם", "משה", "נח", "דוד"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-029",
    prompt: "איזו ציפור שלח נח מהתיבה והיא חזרה עם עלה זית?",
    choices: ["יונה", "עורב", "נשר", "תרנגול"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "torah-030",
    prompt: "מי היה אחיו של משה?",
    choices: ["יוסף", "אהרון", "יהושע", "כלב"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "torah-031",
    prompt: "מי הייתה אחותם של משה ואהרון?",
    choices: ["שרה", "רבקה", "מרים", "לאה"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-032",
    prompt: "כמה בנים היו ליעקב?",
    choices: ["10", "11", "12", "13"],
    correctIndex: 2,
    level: "young",
  },
  {
    id: "torah-033",
    prompt: "מי קיבל כתונת פסים מאביו?",
    choices: ["ראובן", "יוסף", "בנימין", "לוי"],
    correctIndex: 1,
    level: "young",
  },
  {
    id: "torah-034",
    prompt: "מה מדליקים בערב שבת?",
    choices: ["נרות", "מדורה", "חנוכייה", "אבוקות"],
    correctIndex: 0,
    level: "young",
  },
  {
    id: "torah-035",
    prompt: "איזה ספר מספר על בריאת העולם?",
    choices: ["שמות", "בראשית", "ויקרא", "דברים"],
    correctIndex: 1,
    level: "young",
  },

  // ---- middle (כיתות ג'-ה') ----
  {
    id: "torah-002",
    prompt: "כמה ימים נמשך מבול נח?",
    choices: ["7 ימים", "40 ימים", "100 ימים", "365 ימים"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-005",
    prompt: "בהר איזה ניתנה התורה?",
    choices: ["הר המוריה", "הר תבור", "הר סיני", "הר חרמון"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "torah-008",
    prompt: "מי היו אמהות עם ישראל?",
    choices: [
      "שרה, רבקה, רחל, לאה",
      "מרים, חנה, רות, אסתר",
      "דבורה, יעל, חולדה, אסתר",
      "תמר, רחב, רות, בת-שבע",
    ],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "torah-010",
    prompt: "כמה נרות מדליקים בלילה האחרון של חנוכה (לא כולל השמש)?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "torah-011",
    prompt: "באיזה חודש חל ראש השנה?",
    choices: ["ניסן", "תמוז", "אלול", "תשרי"],
    correctIndex: 3,
    level: "middle",
  },
  {
    id: "torah-012",
    prompt: "מהו היום הקדוש ביותר בשנה היהודית?",
    choices: ["ראש השנה", "יום כיפור", "פסח", "שבועות"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-014",
    prompt: "מהי המגילה שקוראים בפורים?",
    choices: ["מגילת רות", "מגילת אסתר", "מגילת איכה", "שיר השירים"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-015",
    prompt: "איזה חג מציין את קבלת התורה?",
    choices: ["פסח", "שבועות", "סוכות", "ראש השנה"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-016",
    prompt: "כמה שבטים היו לבני ישראל?",
    choices: ["10", "12", "13", "14"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-020",
    prompt: 'מי "מלחמת דוד עם" — הניסיון הקלאסי של הקטן מול הגדול?',
    choices: ["עמלק", "גוליית", "פרעה", "המן"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-022",
    prompt: "מהי הברכה הראשונה בכל ארוחה עם לחם?",
    choices: ["שהכל", "המוציא", "בורא פרי האדמה", "בורא נפשות"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-025",
    prompt: "כמה ימים נמשך חג סוכות (לא כולל שמיני עצרת)?",
    choices: ["5", "6", "7", "8"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "torah-036",
    prompt: "מהו סדר חמשת חומשי התורה?",
    choices: [
      "בראשית, שמות, ויקרא, במדבר, דברים",
      "שמות, בראשית, ויקרא, דברים, במדבר",
      "בראשית, ויקרא, שמות, במדבר, דברים",
      "בראשית, שמות, במדבר, ויקרא, דברים",
    ],
    correctIndex: 0,
    level: "middle",
  },
  {
    id: "torah-037",
    prompt: "כמה מכות הביא ה' על מצרים?",
    choices: ["7", "8", "10", "12"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "torah-038",
    prompt: "מה הייתה המכה האחרונה ממכות מצרים?",
    choices: ["דם", "חושך", "ברד", "מכת בכורות"],
    correctIndex: 3,
    level: "middle",
  },
  {
    id: "torah-039",
    prompt: "כמה שנים הלכו בני ישראל במדבר?",
    choices: ["10", "20", "40", "70"],
    correctIndex: 2,
    level: "middle",
  },
  {
    id: "torah-040",
    prompt: "איזה ים נבקע כשיצאו בני ישראל ממצרים?",
    choices: ["הים התיכון", "ים סוף", "ים המלח", "הכנרת"],
    correctIndex: 1,
    level: "middle",
  },
  {
    id: "torah-041",
    prompt: "מה אכלו בני ישראל במדבר?",
    choices: ["מן", "לחם", "דגים", "פירות"],
    correctIndex: 0,
    level: "middle",
  },

  // ---- older (כיתות ו' ומעלה) ----
  {
    id: "torah-017",
    prompt: "מי בנה את בית המקדש הראשון?",
    choices: ["דוד המלך", "שלמה המלך", "שאול המלך", "חזקיהו המלך"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-018",
    prompt: "מי כתב את ספר תהילים?",
    choices: ["משה", "דוד המלך", "שלמה המלך", "שמואל"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-021",
    prompt: 'כמה הם ה-ל"ט מלאכות?',
    choices: ["29", "39", "49", "59"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-024",
    prompt: "מי היה הנביא שעלה ברוח סערה השמיימה?",
    choices: ["ישעיהו", "ירמיהו", "אליהו", "יחזקאל"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "torah-042",
    prompt: "כמה מרגלים שלח משה לתור את הארץ?",
    choices: ["10", "12", "14", "40"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-043",
    prompt: "מי משני המרגלים דיברו טוב על הארץ?",
    choices: ["יהושע וכלב", "דתן ואבירם", "נדב ואביהוא", "משה ואהרון"],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "torah-044",
    prompt: "מי הנהיג את בני ישראל אחרי מות משה?",
    choices: ["אהרון", "כלב", "יהושע", "פנחס"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "torah-045",
    prompt: "באיזה חומש מופיעות עשרת הדיברות לראשונה?",
    choices: ["בראשית", "שמות", "ויקרא", "דברים"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-046",
    prompt: "מי היה הכהן הגדול הראשון?",
    choices: ["משה", "אהרון", "אלעזר", "פנחס"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-047",
    prompt: "מה שמו של ההר שממנו ראה משה את הארץ לפני מותו?",
    choices: ["הר סיני", "הר נבו", "הר תבור", "הר הכרמל"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-048",
    prompt: 'כמה ספרים יש בתנ"ך לפי המסורת?',
    choices: ["18", "24", "27", "36"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-049",
    prompt: "איזו פרשה היא הראשונה בתורה?",
    choices: ["נח", "לך לך", "בראשית", "וירא"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "torah-050",
    prompt: 'מהי מצוות "פאה"?',
    choices: ["להשאיר פינה בשדה לעניים", "לתת מעשר", "לשמור שבת", "לכבד הורים"],
    correctIndex: 0,
    level: "older",
  },
  {
    id: "torah-051",
    prompt: "בת כמה הייתה שרה כשנולד יצחק?",
    choices: ["70", "80", "90", "100"],
    correctIndex: 2,
    level: "older",
  },
  {
    id: "torah-052",
    prompt: "מי מכר את בכורתו תמורת נזיד עדשים?",
    choices: ["יעקב", "עשו", "ראובן", "יוסף"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-053",
    prompt: "כיצד נקרא יעקב לאחר שנאבק עם המלאך?",
    choices: ["ישורון", "ישראל", "יהודה", "אפרים"],
    correctIndex: 1,
    level: "older",
  },
  {
    id: "torah-054",
    prompt: 'מהו "מעשר"?',
    choices: ["עשירית מהיבול הניתנת ללוי או לעני", "שם של חג", "סוג של תפילה", "קורבן חגיגי"],
    correctIndex: 0,
    level: "older",
  },
];

export default QUESTIONS;
