/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ChildRouteImport } from './routes/child'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentTransactionsRouteImport } from './routes/parent/transactions'
import { Route as ParentDashboardRouteImport } from './routes/parent/dashboard'
import { Route as ParentChildrenRouteImport } from './routes/parent/children'
import { Route as ChildWalletRouteImport } from './routes/child/wallet'
import { Route as ChildSavingsRouteImport } from './routes/child/savings'
import { Route as ChildEducateRouteImport } from './routes/child/educate'
import { Route as ChildDashboardRouteImport } from './routes/child/dashboard'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ParentTutorsIndexRouteImport } from './routes/parent/tutors.index'
import { Route as ParentChildrenIndexRouteImport } from './routes/parent/children.index'
import { Route as ChildTutorsIndexRouteImport } from './routes/child/tutors.index'
import { Route as ChildEducateIndexRouteImport } from './routes/child/educate.index'
import { Route as ParentTutorsNewRouteImport } from './routes/parent/tutors.new'
import { Route as ParentTutorsTutorIdRouteImport } from './routes/parent/tutors.$tutorId'
import { Route as ParentTasksNewRouteImport } from './routes/parent/tasks.new'
import { Route as ParentTasksTaskIdRouteImport } from './routes/parent/tasks.$taskId'
import { Route as ParentChildrenNewRouteImport } from './routes/parent/children.new'
import { Route as ChildTutorsTutorIdRouteImport } from './routes/child/tutors.$tutorId'
import { Route as ChildTasksTaskIdRouteImport } from './routes/child/tasks.$taskId'
import { Route as ChildEducateSubjectRouteImport } from './routes/child/educate.$subject'
import { Route as ParentTutorsTutorIdSessionsSessionIdRouteImport } from './routes/parent/tutors.$tutorId.sessions.$sessionId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTransactionsRoute = ParentTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const ChildWalletRoute = ChildWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ChildRoute,
} as any)
const ChildSavingsRoute = ChildSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => ChildRoute,
} as any)
const ChildEducateRoute = ChildEducateRouteImport.update({
  id: '/educate',
  path: '/educate',
  getParentRoute: () => ChildRoute,
} as any)
const ChildDashboardRoute = ChildDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ChildRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ParentTutorsIndexRoute = ParentTutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenIndexRoute = ParentChildrenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentChildrenRoute,
} as any)
const ChildTutorsIndexRoute = ChildTutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => ChildRoute,
} as any)
const ChildEducateIndexRoute = ChildEducateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChildEducateRoute,
} as any)
const ParentTutorsNewRoute = ParentTutorsNewRouteImport.update({
  id: '/tutors/new',
  path: '/tutors/new',
  getParentRoute: () => ParentRoute,
} as any)
const ParentTutorsTutorIdRoute = ParentTutorsTutorIdRouteImport.update({
  id: '/tutors/$tutorId',
  path: '/tutors/$tutorId',
  getParentRoute: () => ParentRoute,
} as any)
const ParentTasksNewRoute = ParentTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => ParentRoute,
} as any)
const ParentTasksTaskIdRoute = ParentTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenNewRoute = ParentChildrenNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ParentChildrenRoute,
} as any)
const ChildTutorsTutorIdRoute = ChildTutorsTutorIdRouteImport.update({
  id: '/tutors/$tutorId',
  path: '/tutors/$tutorId',
  getParentRoute: () => ChildRoute,
} as any)
const ChildTasksTaskIdRoute = ChildTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => ChildRoute,
} as any)
const ChildEducateSubjectRoute = ChildEducateSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => ChildEducateRoute,
} as any)
const ParentTutorsTutorIdSessionsSessionIdRoute =
  ParentTutorsTutorIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => ParentTutorsTutorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/child': typeof ChildRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/child/dashboard': typeof ChildDashboardRoute
  '/child/educate': typeof ChildEducateRouteWithChildren
  '/child/savings': typeof ChildSavingsRoute
  '/child/wallet': typeof ChildWalletRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/child/educate/$subject': typeof ChildEducateSubjectRoute
  '/child/tasks/$taskId': typeof ChildTasksTaskIdRoute
  '/child/tutors/$tutorId': typeof ChildTutorsTutorIdRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/tasks/$taskId': typeof ParentTasksTaskIdRoute
  '/parent/tasks/new': typeof ParentTasksNewRoute
  '/parent/tutors/$tutorId': typeof ParentTutorsTutorIdRouteWithChildren
  '/parent/tutors/new': typeof ParentTutorsNewRoute
  '/child/educate/': typeof ChildEducateIndexRoute
  '/child/tutors/': typeof ChildTutorsIndexRoute
  '/parent/children/': typeof ParentChildrenIndexRoute
  '/parent/tutors/': typeof ParentTutorsIndexRoute
  '/parent/tutors/$tutorId/sessions/$sessionId': typeof ParentTutorsTutorIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/child': typeof ChildRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/child/dashboard': typeof ChildDashboardRoute
  '/child/savings': typeof ChildSavingsRoute
  '/child/wallet': typeof ChildWalletRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/child/educate/$subject': typeof ChildEducateSubjectRoute
  '/child/tasks/$taskId': typeof ChildTasksTaskIdRoute
  '/child/tutors/$tutorId': typeof ChildTutorsTutorIdRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/tasks/$taskId': typeof ParentTasksTaskIdRoute
  '/parent/tasks/new': typeof ParentTasksNewRoute
  '/parent/tutors/$tutorId': typeof ParentTutorsTutorIdRouteWithChildren
  '/parent/tutors/new': typeof ParentTutorsNewRoute
  '/child/educate': typeof ChildEducateIndexRoute
  '/child/tutors': typeof ChildTutorsIndexRoute
  '/parent/children': typeof ParentChildrenIndexRoute
  '/parent/tutors': typeof ParentTutorsIndexRoute
  '/parent/tutors/$tutorId/sessions/$sessionId': typeof ParentTutorsTutorIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/child': typeof ChildRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/child/dashboard': typeof ChildDashboardRoute
  '/child/educate': typeof ChildEducateRouteWithChildren
  '/child/savings': typeof ChildSavingsRoute
  '/child/wallet': typeof ChildWalletRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/child/educate/$subject': typeof ChildEducateSubjectRoute
  '/child/tasks/$taskId': typeof ChildTasksTaskIdRoute
  '/child/tutors/$tutorId': typeof ChildTutorsTutorIdRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/tasks/$taskId': typeof ParentTasksTaskIdRoute
  '/parent/tasks/new': typeof ParentTasksNewRoute
  '/parent/tutors/$tutorId': typeof ParentTutorsTutorIdRouteWithChildren
  '/parent/tutors/new': typeof ParentTutorsNewRoute
  '/child/educate/': typeof ChildEducateIndexRoute
  '/child/tutors/': typeof ChildTutorsIndexRoute
  '/parent/children/': typeof ParentChildrenIndexRoute
  '/parent/tutors/': typeof ParentTutorsIndexRoute
  '/parent/tutors/$tutorId/sessions/$sessionId': typeof ParentTutorsTutorIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/child'
    | '/parent'
    | '/sitemap.xml'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/child/dashboard'
    | '/child/educate'
    | '/child/savings'
    | '/child/wallet'
    | '/parent/children'
    | '/parent/dashboard'
    | '/parent/transactions'
    | '/child/educate/$subject'
    | '/child/tasks/$taskId'
    | '/child/tutors/$tutorId'
    | '/parent/children/new'
    | '/parent/tasks/$taskId'
    | '/parent/tasks/new'
    | '/parent/tutors/$tutorId'
    | '/parent/tutors/new'
    | '/child/educate/'
    | '/child/tutors/'
    | '/parent/children/'
    | '/parent/tutors/'
    | '/parent/tutors/$tutorId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/child'
    | '/parent'
    | '/sitemap.xml'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/child/dashboard'
    | '/child/savings'
    | '/child/wallet'
    | '/parent/dashboard'
    | '/parent/transactions'
    | '/child/educate/$subject'
    | '/child/tasks/$taskId'
    | '/child/tutors/$tutorId'
    | '/parent/children/new'
    | '/parent/tasks/$taskId'
    | '/parent/tasks/new'
    | '/parent/tutors/$tutorId'
    | '/parent/tutors/new'
    | '/child/educate'
    | '/child/tutors'
    | '/parent/children'
    | '/parent/tutors'
    | '/parent/tutors/$tutorId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/child'
    | '/parent'
    | '/sitemap.xml'
    | '/_auth/login'
    | '/_auth/signup'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/child/dashboard'
    | '/child/educate'
    | '/child/savings'
    | '/child/wallet'
    | '/parent/children'
    | '/parent/dashboard'
    | '/parent/transactions'
    | '/child/educate/$subject'
    | '/child/tasks/$taskId'
    | '/child/tutors/$tutorId'
    | '/parent/children/new'
    | '/parent/tasks/$taskId'
    | '/parent/tasks/new'
    | '/parent/tutors/$tutorId'
    | '/parent/tutors/new'
    | '/child/educate/'
    | '/child/tutors/'
    | '/parent/children/'
    | '/parent/tutors/'
    | '/parent/tutors/$tutorId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChildRoute: typeof ChildRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/transactions': {
      id: '/parent/transactions'
      path: '/transactions'
      fullPath: '/parent/transactions'
      preLoaderRoute: typeof ParentTransactionsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/child/wallet': {
      id: '/child/wallet'
      path: '/wallet'
      fullPath: '/child/wallet'
      preLoaderRoute: typeof ChildWalletRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/savings': {
      id: '/child/savings'
      path: '/savings'
      fullPath: '/child/savings'
      preLoaderRoute: typeof ChildSavingsRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/educate': {
      id: '/child/educate'
      path: '/educate'
      fullPath: '/child/educate'
      preLoaderRoute: typeof ChildEducateRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/dashboard': {
      id: '/child/dashboard'
      path: '/dashboard'
      fullPath: '/child/dashboard'
      preLoaderRoute: typeof ChildDashboardRouteImport
      parentRoute: typeof ChildRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/parent/tutors/': {
      id: '/parent/tutors/'
      path: '/tutors'
      fullPath: '/parent/tutors/'
      preLoaderRoute: typeof ParentTutorsIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children/': {
      id: '/parent/children/'
      path: '/'
      fullPath: '/parent/children/'
      preLoaderRoute: typeof ParentChildrenIndexRouteImport
      parentRoute: typeof ParentChildrenRoute
    }
    '/child/tutors/': {
      id: '/child/tutors/'
      path: '/tutors'
      fullPath: '/child/tutors/'
      preLoaderRoute: typeof ChildTutorsIndexRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/educate/': {
      id: '/child/educate/'
      path: '/'
      fullPath: '/child/educate/'
      preLoaderRoute: typeof ChildEducateIndexRouteImport
      parentRoute: typeof ChildEducateRoute
    }
    '/parent/tutors/new': {
      id: '/parent/tutors/new'
      path: '/tutors/new'
      fullPath: '/parent/tutors/new'
      preLoaderRoute: typeof ParentTutorsNewRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/tutors/$tutorId': {
      id: '/parent/tutors/$tutorId'
      path: '/tutors/$tutorId'
      fullPath: '/parent/tutors/$tutorId'
      preLoaderRoute: typeof ParentTutorsTutorIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/tasks/new': {
      id: '/parent/tasks/new'
      path: '/tasks/new'
      fullPath: '/parent/tasks/new'
      preLoaderRoute: typeof ParentTasksNewRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/tasks/$taskId': {
      id: '/parent/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/parent/tasks/$taskId'
      preLoaderRoute: typeof ParentTasksTaskIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children/new': {
      id: '/parent/children/new'
      path: '/new'
      fullPath: '/parent/children/new'
      preLoaderRoute: typeof ParentChildrenNewRouteImport
      parentRoute: typeof ParentChildrenRoute
    }
    '/child/tutors/$tutorId': {
      id: '/child/tutors/$tutorId'
      path: '/tutors/$tutorId'
      fullPath: '/child/tutors/$tutorId'
      preLoaderRoute: typeof ChildTutorsTutorIdRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/tasks/$taskId': {
      id: '/child/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/child/tasks/$taskId'
      preLoaderRoute: typeof ChildTasksTaskIdRouteImport
      parentRoute: typeof ChildRoute
    }
    '/child/educate/$subject': {
      id: '/child/educate/$subject'
      path: '/$subject'
      fullPath: '/child/educate/$subject'
      preLoaderRoute: typeof ChildEducateSubjectRouteImport
      parentRoute: typeof ChildEducateRoute
    }
    '/parent/tutors/$tutorId/sessions/$sessionId': {
      id: '/parent/tutors/$tutorId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/parent/tutors/$tutorId/sessions/$sessionId'
      preLoaderRoute: typeof ParentTutorsTutorIdSessionsSessionIdRouteImport
      parentRoute: typeof ParentTutorsTutorIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ChildEducateRouteChildren {
  ChildEducateSubjectRoute: typeof ChildEducateSubjectRoute
  ChildEducateIndexRoute: typeof ChildEducateIndexRoute
}

const ChildEducateRouteChildren: ChildEducateRouteChildren = {
  ChildEducateSubjectRoute: ChildEducateSubjectRoute,
  ChildEducateIndexRoute: ChildEducateIndexRoute,
}

const ChildEducateRouteWithChildren = ChildEducateRoute._addFileChildren(
  ChildEducateRouteChildren,
)

interface ChildRouteChildren {
  ChildDashboardRoute: typeof ChildDashboardRoute
  ChildEducateRoute: typeof ChildEducateRouteWithChildren
  ChildSavingsRoute: typeof ChildSavingsRoute
  ChildWalletRoute: typeof ChildWalletRoute
  ChildTasksTaskIdRoute: typeof ChildTasksTaskIdRoute
  ChildTutorsTutorIdRoute: typeof ChildTutorsTutorIdRoute
  ChildTutorsIndexRoute: typeof ChildTutorsIndexRoute
}

const ChildRouteChildren: ChildRouteChildren = {
  ChildDashboardRoute: ChildDashboardRoute,
  ChildEducateRoute: ChildEducateRouteWithChildren,
  ChildSavingsRoute: ChildSavingsRoute,
  ChildWalletRoute: ChildWalletRoute,
  ChildTasksTaskIdRoute: ChildTasksTaskIdRoute,
  ChildTutorsTutorIdRoute: ChildTutorsTutorIdRoute,
  ChildTutorsIndexRoute: ChildTutorsIndexRoute,
}

const ChildRouteWithChildren = ChildRoute._addFileChildren(ChildRouteChildren)

interface ParentChildrenRouteChildren {
  ParentChildrenNewRoute: typeof ParentChildrenNewRoute
  ParentChildrenIndexRoute: typeof ParentChildrenIndexRoute
}

const ParentChildrenRouteChildren: ParentChildrenRouteChildren = {
  ParentChildrenNewRoute: ParentChildrenNewRoute,
  ParentChildrenIndexRoute: ParentChildrenIndexRoute,
}

const ParentChildrenRouteWithChildren = ParentChildrenRoute._addFileChildren(
  ParentChildrenRouteChildren,
)

interface ParentTutorsTutorIdRouteChildren {
  ParentTutorsTutorIdSessionsSessionIdRoute: typeof ParentTutorsTutorIdSessionsSessionIdRoute
}

const ParentTutorsTutorIdRouteChildren: ParentTutorsTutorIdRouteChildren = {
  ParentTutorsTutorIdSessionsSessionIdRoute:
    ParentTutorsTutorIdSessionsSessionIdRoute,
}

const ParentTutorsTutorIdRouteWithChildren =
  ParentTutorsTutorIdRoute._addFileChildren(ParentTutorsTutorIdRouteChildren)

interface ParentRouteChildren {
  ParentChildrenRoute: typeof ParentChildrenRouteWithChildren
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentTransactionsRoute: typeof ParentTransactionsRoute
  ParentTasksTaskIdRoute: typeof ParentTasksTaskIdRoute
  ParentTasksNewRoute: typeof ParentTasksNewRoute
  ParentTutorsTutorIdRoute: typeof ParentTutorsTutorIdRouteWithChildren
  ParentTutorsNewRoute: typeof ParentTutorsNewRoute
  ParentTutorsIndexRoute: typeof ParentTutorsIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentChildrenRoute: ParentChildrenRouteWithChildren,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentTransactionsRoute: ParentTransactionsRoute,
  ParentTasksTaskIdRoute: ParentTasksTaskIdRoute,
  ParentTasksNewRoute: ParentTasksNewRoute,
  ParentTutorsTutorIdRoute: ParentTutorsTutorIdRouteWithChildren,
  ParentTutorsNewRoute: ParentTutorsNewRoute,
  ParentTutorsIndexRoute: ParentTutorsIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ChildRoute: ChildRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
